heat_template_version: queens

parameters:
  ControlPlaneIp:
    default: ''
    type: string
  ControlPlaneSubnetCidr: # Override this via parameter_defaults
    default: '24'
    description: The subnet CIDR of the control plane network.
    type: string
  StorageIp:
    default: ''
    type: string
  StorageIpSubnet:
    description: 'IP address/subnet on the storage network'
    default: ''
    type: string
  StorageIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  StorageMgmtIp:
    default: ''
    type: string
  StorageMgmtIpSubnet:
    description: 'IP address/subnet on the storage_mgmt network'
    default: ''
    type: string
  StorageMgmtIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  InternalApiIp:
    default: ''
    type: string
  InternalApiIpSubnet:
    description: 'IP address/subnet on the internal_api network'
    default: ''
    type: string
  InternalApiIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  TenantIp:
    default: ''
    type: string
  TenantIpSubnet:
    description: 'IP address/subnet on the tenant network'
    default: ''
    type: string
  TenantIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  ManagementIp:
    default: ''
    type: string
  ManagementIpSubnet:
    description: 'IP address/subnet on the management network'
    default: ''
    type: string
  ManagementIpUri:
    default: ''
    type: string
    description: IP address with brackets in case of IPv6
  StorageNetName:
    default: storage
    description: The name of the storage network.
    type: string
  StorageMgmtNetName:
    default: storage_mgmt
    description: The name of the storage_mgmt network.
    type: string
  InternalApiNetName:
    default: internal_api
    description: The name of the internal_api network.
    type: string
  TenantNetName:
    default: tenant
    description: The name of the tenant network.
    type: string
  ManagementNetName:
    default: management
    description: The name of the management network.
    type: string

resources:

  NetIpMapValue:
    type: OS::Heat::Value
    properties:
      type: json
      value:
        map_replace:
          - ctlplane: {get_param: ControlPlaneIp}
            storage: {get_param: StorageIp}
            storage_mgmt: {get_param: StorageMgmtIp}
            internal_api: {get_param: InternalApiIp}
            tenant: {get_param: TenantIp}
            management: {get_param: ManagementIp}
            ctlplane_subnet:
              list_join:
                - ''
                - - {get_param: ControlPlaneIp}
                  - '/'
                  - {get_param: ControlPlaneSubnetCidr}
            storage_subnet: {get_param: StorageIpSubnet}
            storage_mgmt_subnet: {get_param: StorageMgmtIpSubnet}
            internal_api_subnet: {get_param: InternalApiIpSubnet}
            tenant_subnet: {get_param: TenantIpSubnet}
            management_subnet: {get_param: ManagementIpSubnet}
            ctlplane_uri: {get_param: ControlPlaneIp}
            storage_uri: {get_param: StorageIpUri}
            storage_mgmt_uri: {get_param: StorageMgmtIpUri}
            internal_api_uri: {get_param: InternalApiIpUri}
            tenant_uri: {get_param: TenantIpUri}
            management_uri: {get_param: ManagementIpUri}
          - keys:
              storage: {get_param: StorageNetName}
              storage_mgmt: {get_param: StorageMgmtNetName}
              internal_api: {get_param: InternalApiNetName}
              tenant: {get_param: TenantNetName}
              management: {get_param: ManagementNetName}
              storage_subnet:
                str_replace:
                  template: NAME_subnet
                  params:
                    NAME: {get_param: StorageNetName}
              storage_mgmt_subnet:
                str_replace:
                  template: NAME_subnet
                  params:
                    NAME: {get_param: StorageMgmtNetName}
              internal_api_subnet:
                str_replace:
                  template: NAME_subnet
                  params:
                    NAME: {get_param: InternalApiNetName}
              tenant_subnet:
                str_replace:
                  template: NAME_subnet
                  params:
                    NAME: {get_param: TenantNetName}
              management_subnet:
                str_replace:
                  template: NAME_subnet
                  params:
                    NAME: {get_param: ManagementNetName}
              storage_uri:
                str_replace:
                  template: NAME_uri
                  params:
                    NAME: {get_param: StorageNetName}
              storage_mgmt_uri:
                str_replace:
                  template: NAME_uri
                  params:
                    NAME: {get_param: StorageMgmtNetName}
              internal_api_uri:
                str_replace:
                  template: NAME_uri
                  params:
                    NAME: {get_param: InternalApiNetName}
              tenant_uri:
                str_replace:
                  template: NAME_uri
                  params:
                    NAME: {get_param: TenantNetName}
              management_uri:
                str_replace:
                  template: NAME_uri
                  params:
                    NAME: {get_param: ManagementNetName}

outputs:
  net_ip_map:
    description: >
      A Hash containing a mapping of network names to assigned IPs
      for a specific machine.
    value: {get_attr: [NetIpMapValue, value]}